export DOT_FILES=$HOME/bin
. $DOT_FILES/bash/env
. $DOT_FILES/bash/config
. $DOT_FILES/bash/aliases
. $DOT_FILES/bash/functions
. $DOT_FILES/git/git_completion

# Method missing for bash.
# http://blog.peepcode.com/tutorials/2009/shell-method-missing
# trap 'if ! type -t $BASH_COMMAND >/dev/null; then ~/bin/misc/shell_method_missing.rb $BASH_COMMAND; fi' DEBUG

# This loads RVM into a shell session.
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"